---
- name: Create a Deployment by reading the definition from a local file
  kubernetes.core.k8s:
    state: present
    src: "{{ manifest_path.dest }}"
    kubeconfig: "{{ kubeconfig | default('~/.kube/config', true) }}"
  tags:
    - download-deploy